services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    container_name: flask_app
    environment:
      DATABASE_URL: postgresql+psycopg2://myuser:mypassword@db:5432/mydb
      SECRET_KEY: mysecretkey
    depends_on:
      - db
    ports:
      - "5000:5000"

volumes:
  pgdata: